
#ifndef KSS18_PARAMS_H
#define KSS18_PARAMS_H

#include <gmp.h>

// KSS18 Curve Parameters (128-bit security level)
// Generated by tools/generate_params.py

// Prime field characteristic p
#define KSS18_P "436857712374078395930663005758751404993683215851180272141288915412463557148414426055585387504617177597711"

// Prime order r of the subgroup G1/G2
#define KSS18_R "86422207708313935047910808484838084148459808739125020171668853409353524599001"

// Curve constant B (E: y^2 = x^3 + B)
#define KSS18_B 3

// Twist constant delta for E' (used for Fp18 construction: X^18 - delta)
// Note: The PRD mentions X^18 - 3, implying delta=3.
#define KSS18_DELTA 3

// Declare global GMP variables (to be defined in a .c file)
extern mpz_t kss18_p;
extern mpz_t kss18_r;
extern mpz_t kss18_b;

// Function to initialize global GMP parameters from defines
static inline void kss18_init_globals() {
    mpz_init_set_str(kss18_p, KSS18_P, 10);
    mpz_init_set_str(kss18_r, KSS18_R, 10);
    mpz_init_set_ui(kss18_b, KSS18_B);
    // DELTA is typically used directly, not as an mpz_t
}

// Function to clear global GMP parameters
static inline void kss18_clear_globals() {
    mpz_clear(kss18_p);
    mpz_clear(kss18_r);
    mpz_clear(kss18_b);
}

#endif // KSS18_PARAMS_H
