import sys
# Add a check for sympy installation and provide instructions if missing
try:
    from sympy import isprime
except ImportError:
    print("Error: sympy library not found.")
    print("Please install it using: pip install sympy")
    sys.exit(1)

# Calculate u = 2^44 + 2^22 - 2^9 + 2
u = pow(2, 44) + pow(2, 22) - pow(2, 9) + 2
print(f"Calculated u = {u}")

# Calculate p = (u^8 + 5u^7 + 7u^6 + 37u^5 + 188u^4 + 259u^3 + 343u^2 + 1763u + 2401) / 21
p_num = pow(u, 8) + 5 * pow(u, 7) + 7 * pow(u, 6) + 37 * pow(u, 5) + 188 * pow(u, 4) + 259 * pow(u, 3) + 343 * pow(u, 2) + 1763 * u + 2401
p = p_num // 21 # Use integer division

# Verify p is integer
if p_num % 21 != 0:
    print(f"Error: Numerator for p ({p_num}) is not divisible by 21.")
    sys.exit(1)

print(f"Calculated p = {p}")

# Calculate r = (u^6 + 37u^3 + 343) / 343
r_num = pow(u, 6) + 37 * pow(u, 3) + 343
r = r_num // 343 # Use integer division

# Verify r is integer
if r_num % 343 != 0:
    print(f"Error: Numerator for r ({r_num}) is not divisible by 343.")
    sys.exit(1)

print(f"Calculated r = {r}")

# Verify primality
print("Verifying primality of p...")
if not isprime(p):
    print(f"Error: Calculated p ({p}) is not prime.")
    sys.exit(1)
print("p is prime.")

print("Verifying primality of r...")
if not isprime(r):
    print(f"Error: Calculated r ({r}) is not prime.")
    sys.exit(1)
print("r is prime.")

# Define other constants
B = 3
DELTA = 3

# Generate C header file content
header_content = f"""
#ifndef KSS18_PARAMS_H
#define KSS18_PARAMS_H

#include <gmp.h>

// KSS18 Curve Parameters (128-bit security level)
// Generated by tools/generate_params.py

// Prime field characteristic p
#define KSS18_P \"{p}\"

// Prime order r of the subgroup G1/G2
#define KSS18_R \"{r}\"

// Curve constant B (E: y^2 = x^3 + B)
#define KSS18_B {B}

// Twist constant delta for E' (used for Fp18 construction: X^18 - delta)
// Note: The PRD mentions X^18 - 3, implying delta=3.
#define KSS18_DELTA {DELTA}

// Declare global GMP variables (to be defined in a .c file)
extern mpz_t kss18_p;
extern mpz_t kss18_r;
extern mpz_t kss18_b;

// Function to initialize global GMP parameters from defines
static inline void kss18_init_globals() {{
    mpz_init_set_str(kss18_p, KSS18_P, 10);
    mpz_init_set_str(kss18_r, KSS18_R, 10);
    mpz_init_set_ui(kss18_b, KSS18_B);
    // DELTA is typically used directly, not as an mpz_t
}}

// Function to clear global GMP parameters
static inline void kss18_clear_globals() {{
    mpz_clear(kss18_p);
    mpz_clear(kss18_r);
    mpz_clear(kss18_b);
}}

#endif // KSS18_PARAMS_H
"""

# Write to header file (absolute path)
header_path = "/workspaces/FiniteExtensionFieldDeg18/parameters.h" # Use absolute path
try:
    with open(header_path, "w") as f:
        f.write(header_content)
    print(f"Successfully wrote parameters to {header_path}")
except IOError as e:
    print(f"Error writing to {header_path}: {e}")
    sys.exit(1)

# Optional: Output sample values (can be added later)
# print("\\nSample Values:")
# print(f"Sample Fp element: ...")
# print(f"Sample E(Fp) point: ...")
# print(f"Sample E'(Fp3) point: ...")
# print(f"Sample Pairing output: ...")

